
server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ead-course
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgresSQLDialect
      jdbc:
        log.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

